-- Eliminar la base de dato SALES
DROP DATABASE SALES;

-- Crear base de datos SALES
CREATE DATABASE IF NOT EXISTS SALES
DEFAULT CHARACTER SET utf8;

-- Poner en uso la base de datos
USE SALES;

-- Crear la tabla CUSTOMER
CREATE TABLE CUSTOMER 
(
    CUSTNO CHAR(8),
    CUSTFIRSTNAME VARCHAR(30) NOT NULL,
    CUSTLASTNAME VARCHAR(30) NOT NULL,
    CUSTCITY VARCHAR(30),
    CUSTSTATE CHAR(2),
    CUSTZIP CHAR(10),
    CUSTBAL DECIMAL(10,2),
    CONSTRAINT CUSTNO_PK PRIMARY KEY(CUSTNO)
);

-- Crear la tabla EMPLOYEE
CREATE TABLE EMPLOYEE 
(
    EMPNO CHAR(8),
    EMPFIRSTNAME VARCHAR(30) NOT NULL,
    EMPLASTNAME VARCHAR(30) NOT NULL,
    EMPPHONE VARCHAR(20),
    EMPEMAIL CHAR(30) NOT NULL,
    CONSTRAINT EMPNO_PK PRIMARY KEY(EMPNO)
);

-- Crear la tabla ORDERTBL
CREATE TABLE ORDERTBL 
(
    ORDNO CHAR(8),
    ORDDATE VARCHAR(30) NOT NULL,
    CUSTNO VARCHAR(30) NOT NULL,
    EMPNO VARCHAR(30) NOT NULL,
    CONSTRAINT ORDNO_PK PRIMARY KEY(ORDNO)
);

-- Relacionar la tabla CUSTOMER con ORDERTBL
ALTER TABLE ORDERTBL
ADD CONSTRAINT CUSTOMER_ORDERTBL_CUSTNO
FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER (CUSTNO);

-- Relacionar la tabla EMPLOYEE con ORDERTBL
ALTER TABLE ORDERTBL
ADD CONSTRAINT EMPLOYEE_ORDERTBL_EMPNO
FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE (EMPNO);